% % File name:        ModelDataProcess
% % Create date:      2022.3.17
% % Writer:           Weyman 
% % Brief:            Set fitting weight, mathmodel argument fitting, save
% %                   argument.
% % Latest change:    2022.11.8
% % Change note:      Additionally saving data of cftool gof 


%% Prepare work
clc;
clear;
close all;


%% Load data
distance = readmatrix('range.txt');
% rssi = 1 + typecast(readmatrix('rssi_raw.txt','OutputType','uint8'),'int8');      % 这里+1的原因是matlab中关于负数转换的机制和传统意义上0-255不一致，他们使用的是256
readrssi = readmatrix('rssi_raw_newtest.txt','OutputType','double');                   % 20220528 changed for artificially input RSSI average value to .txt file, change the datatype
rssi = readrssi(:,3);

%% Raw data weight process
weight = ones(length(rssi),1);
weight(20:25,1) = 0.1;      % math basis depends


%% Curve fitting base on cftool generated code 
[fitresult, gof] = createFit(distance, rssi, weight);       % fun generated by cftool with weight .m script store in 0622/mathmodel
fitoutput.a = fitresult.a;
fitoutput.n = fitresult.n;
save('mathmodel_argument.txt','-struct','fitoutput','-ascii');
save('fitgof.mat','-struct','gof');




% %% Draw data figure to adjust data weight
% figure;
% scatter(distance, rssi,'MarkerEdgeColor','#0072BD','MarkerFaceColor','#0072BD');
% title('RSSI data from 0.25m to 10m');
% ylabel('RSSI (dbm)');
% xlabel('distance (d)');
% grid on;


